set(_CATKIN_CURRENT_PACKAGE "zavtrav3")
set(zavtrav3_VERSION "0.0.0")
set(zavtrav3_MAINTAINER "ilya <ilya@todo.todo>")
set(zavtrav3_PACKAGE_FORMAT "2")
set(zavtrav3_BUILD_DEPENDS "diagnostic_msgs" "dynamic_reconfigure" "gazebo_ros" "geometry_msgs" "message_generation" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "turtlebot3_msgs")
set(zavtrav3_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "dynamic_reconfigure" "gazebo_ros" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "turtlebot3_msgs")
set(zavtrav3_BUILDTOOL_DEPENDS "catkin")
set(zavtrav3_BUILDTOOL_EXPORT_DEPENDS )
set(zavtrav3_EXEC_DEPENDS "diagnostic_msgs" "dynamic_reconfigure" "gazebo_ros" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "turtlebot3_msgs")
set(zavtrav3_RUN_DEPENDS "diagnostic_msgs" "dynamic_reconfigure" "gazebo_ros" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "turtlebot3_msgs")
set(zavtrav3_TEST_DEPENDS )
set(zavtrav3_DOC_DEPENDS )
set(zavtrav3_URL_WEBSITE "")
set(zavtrav3_URL_BUGTRACKER "")
set(zavtrav3_URL_REPOSITORY "")
set(zavtrav3_DEPRECATED "")